{"name": "test_auth", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'get'", "trace": "def test_auth():\n        email = \"lapushkagg8@gmail.com\"\n        password = \"jdKZxUV4mFC6i\"\n        username = \"Елизавета Сигарева\"\n    \n        auth_page = AuthPage(browser)\n>       auth_page.go()\n\ntest\\simple_test.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Authpage.AuthPage object at 0x000001FA400D2660>\n\n    @allure.step(\"Перейти на страницу авторизации\")\n    def go(self):\n>       self.__driver.get(self.__url)\nE       AttributeError: 'function' object has no attribute 'get'\n\npages\\Authpage.py:15: AttributeError"}, "steps": [{"name": "Перейти на страницу авторизации", "status": "broken", "statusDetails": {"message": "AttributeError: 'function' object has no attribute 'get'\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\user\\Desktop\\skypro\\final_proj\\pytest_ui_api_template\\pages\\Authpage.py\", line 15, in go\n    self.__driver.get(self.__url)\n    ^^^^^^^^^^^^^^^^^\n"}, "start": 1737623084738, "stop": 1737623084738}], "start": 1737623084738, "stop": 1737623084739, "uuid": "5ccc4782-54d5-4168-9458-e529db3c8cd2", "historyId": "c632045a4697976c7300dedd6d801a19", "testCaseId": "c632045a4697976c7300dedd6d801a19", "fullName": "test.simple_test#test_auth", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "simple_test"}, {"name": "host", "value": "TEG"}, {"name": "thread", "value": "19644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.simple_test"}]}