{"uuid": "a8ebeebf-d8c3-4bd5-8f71-9ac71dee848c", "children": ["e3f1c8e6-992c-4524-b2c8-3a9aaf3fc1c5"], "befores": [{"name": "api_client", "status": "broken", "statusDetails": {"message": "KeyError: 'api'\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\user\\Desktop\\skypro\\final_proj\\pytest_ui_api_template\\test\\conftest.py\", line 23, in api_client\n    url = ConfigProvider().getint(\"api\", \"base_url\")\n  File \"C:\\Users\\user\\Desktop\\skypro\\final_proj\\pytest_ui_api_template\\conficuration\\configprovider.py\", line 13, in getint\n    return self.config[section].getint(prop)\n           ~~~~~~~~~~~^^^^^^^^^\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\configparser.py\", line 998, in __getitem__\n    raise KeyError(key)\n"}, "start": 1737632926447, "stop": 1737632926448}], "start": 1737632926447, "stop": 1737632926468}